import type { AnonymousDealBreakdown } from "@/lib/types";

/**
 * Hardcoded breakdown for the public sample contract page.
 *
 * Generated by running the contract through the analysis pipeline
 * (scripts/analyze-sample-contract.ts) and then correcting fields
 * the heuristic layer misread. Once the LLM layer is live in prod,
 * re-run the script and replace this file with the output.
 */
export const SAMPLE_CONTRACT_BREAKDOWN: AnonymousDealBreakdown = {
  brandName: "Northstar Skin",
  contractTitle: "Northstar Skin Spring Glow Campaign",
  contractSummary:
    "This is a creator partnership agreement between Northstar Skin LLC and Avery Monroe for the Spring Glow campaign promoting the Northstar Skin cleanser and serum collection. The campaign runs March 10 through March 30, 2026, across TikTok and Instagram. The creator is paid a flat $2,500 fee within 60 days of the final approved post. The contract grants the brand perpetual, worldwide usage rights with no cap on media spend or channel, which is unusually broad. There is a 30-day post-campaign exclusivity window for skincare cleansers and serums. The contract includes no late-payment penalty, no kill fee, and no milestone payments, leaving the creator with limited leverage if the brand delays payment.",
  paymentAmount: 2500,
  currency: "USD",
  paymentSummary:
    "Flat fee of $2,500, split evenly between TikTok and Instagram for internal accounting. Payment is due within 60 days after the final approved post goes live. No milestone payments, no prepayment, no rush fee, and no late-payment penalty or interest clause.",
  deliverables: [
    {
      id: "sample-deliverable-1",
      title: "TikTok post",
      dueDate: "2026-03-18",
      channel: "TikTok",
      quantity: 3,
      status: "pending",
      description:
        "Three creator-owned videos featuring the Spring Glow cleanser and serum, each between 20 and 45 seconds. Must feature product in a personal skincare routine context with a clear spoken or on-screen callout to the Spring Glow collection. Product must be held in frame within the first five seconds.",
      source: "Section 2, Deliverables and posting timeline"
    },
    {
      id: "sample-deliverable-2",
      title: "Instagram story",
      dueDate: "2026-03-30",
      channel: "Instagram",
      quantity: 2,
      status: "pending",
      description:
        "Two supporting story frames tied to the launch window. One swipe-up link frame directing to the launch page and one product routine frame. Must include visible paid partnership disclosure.",
      source: "Section 2, Deliverables and posting timeline"
    }
  ],
  riskFlags: [
    {
      id: "risk-1",
      title: "Perpetual, irrevocable usage rights with no cap",
      detail:
        "Section 6 grants the brand a worldwide, transferable, sublicensable, perpetual, irrevocable license covering all media now known or later developed. There is no media spend cap, no geographic limit, no channel limit, and no end date. The creator also waives the right to inspect or approve derivative edits. This is significantly broader than typical creator deals and means the brand can use the content forever in any context without additional compensation.",
      severity: "high",
      suggestedAction:
        "Negotiate a fixed usage term (e.g. 12 months) with a separate paid-media buyout fee. Remove the waiver of approval rights for derivative edits."
    },
    {
      id: "risk-2",
      title: "Paid usage included without separate compensation",
      detail:
        "The perpetual license in Section 6 explicitly includes paid media, whitelabeling, boosting, ecommerce, retail, broadcast, and streaming. There is no additional fee or cap for paid amplification of the creator's content, meaning the brand can run unlimited ad spend using the creator's likeness for the same flat $2,500 fee.",
      severity: "high",
      suggestedAction:
        "Confirm channels, duration, and added compensation for paid usage. Consider a separate whitelisting or boosting fee."
    },
    {
      id: "risk-3",
      title: "No late-payment remedy or kill fee",
      detail:
        "Section 4 explicitly states there is no rush fee, milestone payment, late fee, interest, collection cost recovery, or automatic suspension remedy. The brand is not required to prepay any portion. If the brand delays payment past the 60-day window, the creator has no contractual leverage to enforce timely payment.",
      severity: "high",
      suggestedAction:
        "Add a late-payment interest clause (e.g. 1.5% per month), a right to pause deliverables if payment is overdue, and a kill fee for work completed if the campaign is cancelled."
    },
    {
      id: "risk-4",
      title: "Likeness and biographical information included in license",
      detail:
        "Section 6 includes the creator's name, likeness, voice, biographical information, social handles, captions, and behind-the-scenes stills in the perpetual license. This means the brand could use the creator's likeness in paid ads indefinitely without further consent.",
      severity: "medium",
      suggestedAction:
        "Limit likeness usage to the campaign period or require separate written approval for paid media featuring the creator's likeness beyond the original deliverables."
    },
    {
      id: "risk-5",
      title: "Brand controls proration on termination",
      detail:
        "Section 11 says if the brand terminates for convenience after work is done, payment is prorated on a basis 'reasonably determined by Brand,' giving the brand unilateral control over how much the creator gets paid for completed work.",
      severity: "medium",
      suggestedAction:
        "Change proration language to a neutral formula (e.g. per-deliverable rate) or require mutual agreement on the prorated amount."
    }
  ],
  documentKind: "contract",
  sourceFileName: "northstar-skin-spring-glow-campaign-contract.pdf"
};
